name: ci
on:
  push:
    branches:
      - main
jobs:
  tasks:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: mariadb
          args: start
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MARIADB_USER: user
          MARIADB_PASSWORD: testrootpass
          MARIADB_DATABASE: todo
      - name: test
        run: fluentci run --wasm django test
        env:
          MARIADB_DATABASE: todo
          MARIADB_USER: user
          MARIADB_PASSWORD: testrootpass
          MARIADB_ROOT_PASSWORD: root
          MARIADB_HOST: 127.0.0.1
